CCS\BaseBundle\Entity\UserGroup:
    type: entity
    table: usergroup
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
